# Generated by Django 5.2.7 on 2025-10-27 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videostream',
            name='video',
        ),
        migrations.AddField(
            model_name='videostream',
            name='started',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videostream',
            name='stopped',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='uploads/videos/')),
                ('chunk_number', models.IntegerField()),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='stream.videostream')),
            ],
        ),
    ]
