# Generated by Django 5.2.7 on 2025-10-27 13:35

import stream.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_remove_videostream_video_videostream_started_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='file_size',
        ),
        migrations.AlterField(
            model_name='chunk',
            name='video_file',
            field=models.FileField(upload_to=stream.models.video_upload_path),
        ),
    ]
