# Generated by Django 5.2.7 on 2025-11-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_remove_chunk_file_size_alter_chunk_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostream',
            name='source',
            field=models.IntegerField(choices=[(0, 'Source Arpi'), (1, 'Source Phone')], default=1),
            preserve_default=False,
        ),
    ]
