# Generated by Django 5.2.8 on 2025-12-03 21:33

import django.db.models.deletion
import stream.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_videostream_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatDetections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_num', models.IntegerField()),
                ('frame_file', models.FileField(upload_to=stream.models.frame_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catdetection', to='stream.chunk')),
            ],
        ),
    ]
