# Generated by Django 5.2.8 on 2025-12-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_catdetections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatDetections',
            new_name='CatDetection',
        ),
    ]
