# Generated by Django 5.2.8 on 2025-12-04 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_rename_catdetections_catdetection'),
    ]

    operations = [
        migrations.AddField(
            model_name='catdetection',
            name='video_stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catdetections_on_vs', to='stream.videostream'),
        ),
        migrations.AlterField(
            model_name='catdetection',
            name='chunk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catdetections_on_chunk', to='stream.chunk'),
        ),
    ]
