# Generated by Django 5.2.7 on 2025-10-26 11:46

import detector.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(verbose_name=detector.models.QueueItem.QUEUE_ITEM_STATE_CHOICES)),
                ('task', models.IntegerField(verbose_name=detector.models.QueueItem.QUEUE_ITEM_TASK_CHOICES)),
                ('task_context', models.JSONField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.videostream')),
            ],
        ),
    ]
