# Generated by Django 5.2.7 on 2025-10-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitem',
            name='state',
            field=models.IntegerField(choices=[(-1, 'Queued'), (0, 'Processing'), (1, 'Finished')]),
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='task',
            field=models.IntegerField(choices=[(0, 'Process Frame Cat Object Detection'), (1, 'Process Frame Cat Object Segmentation'), (2, 'Process Frame Cat Reid Categorization')]),
        ),
    ]
